// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*Generate)(nil)

type Generate struct {
	*Iso
	Flags           *flag.FlagSet
	profile         string
	dry             bool
	includeData     bool
	index           int
	outputDirectory string
	SubCommands     map[string]Cmd
}

type UsageDataGenerate struct {
	*Generate
	Recursive bool
}

func (c *Generate) Usage() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) UsageRecursive() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value

			case "dry":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.dry = b
				} else {
					c.dry = true
				}

			case "includeData", "include-data":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.includeData = b
				} else {
					c.includeData = true
				}

			case "index", "1":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.index = iv

			case "outputDirectory", "output-dir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.outputDirectory = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := commands.IsoGenerate(c.profile, c.dry, c.includeData, c.index, c.outputDirectory); err != nil {
		return fmt.Errorf("generate failed: %w", err)
	}

	return nil
}

func (c *Iso) NewGenerate() *Generate {
	set := flag.NewFlagSet("generate", flag.ContinueOnError)
	v := &Generate{
		Iso:         c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")

	set.BoolVar(&v.dry, "dry", true, "When this is true it's a dry run and doesn't save changes")

	set.BoolVar(&v.includeData, "include-data", true, "Include the profile data for backup sake")

	set.IntVar(&v.index, "index", -1, "The chosen disk index number see disk list")
	set.IntVar(&v.index, "1", -1, "The chosen disk index number see disk list")

	set.StringVar(&v.outputDirectory, "output-dir", ".", "Directory to output the ISO")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
