// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*ListDisks)(nil)

type ListDisks struct {
	*Disk
	Flags       *flag.FlagSet
	profile     string
	SubCommands map[string]Cmd
}

type UsageDataListDisks struct {
	*ListDisks
	Recursive bool
}

func (c *ListDisks) Usage() {
	err := executeUsage(os.Stderr, "list-disks_usage.txt", UsageDataListDisks{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ListDisks) UsageRecursive() {
	err := executeUsage(os.Stderr, "list-disks_usage.txt", UsageDataListDisks{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ListDisks) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := commands.DiskList(c.profile); err != nil {
		return fmt.Errorf("list-disks failed: %w", err)
	}

	return nil
}

func (c *Disk) NewListDisks() *ListDisks {
	set := flag.NewFlagSet("list-disks", flag.ContinueOnError)
	v := &ListDisks{
		Disk:        c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
