// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"github.com/arran4/podcast-cdr-manager/cmd"
	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*ListSubs)(nil)

type ListSubs struct {
	*Subscriptions
	Flags         *flag.FlagSet
	profile       string
	SubCommands   map[string]Cmd
	CommandAction func(c *ListSubs) error
}

type UsageDataListSubs struct {
	*ListSubs
	Recursive bool
}

func (c *ListSubs) Usage() {
	err := executeUsage(os.Stderr, "list-subs_usage.txt", UsageDataListSubs{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ListSubs) UsageRecursive() {
	err := executeUsage(os.Stderr, "list-subs_usage.txt", UsageDataListSubs{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ListSubs) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("list-subs failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Subscriptions) NewListSubs() *ListSubs {
	set := flag.NewFlagSet("list-subs", flag.ContinueOnError)
	v := &ListSubs{
		Subscriptions: c,
		Flags:         set,
		SubCommands:   make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")
	set.Usage = v.Usage

	v.CommandAction = func(c *ListSubs) error {

		err := commands.SubscriptionsList(c.profile)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("list-subs failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
