// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*New)(nil)

type New struct {
	*Profile
	Flags       *flag.FlagSet
	profile     string
	force       bool
	name        string
	SubCommands map[string]Cmd
}

type UsageDataNew struct {
	*New
	Recursive bool
}

func (c *New) Usage() {
	err := executeUsage(os.Stderr, "new_usage.txt", UsageDataNew{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *New) UsageRecursive() {
	err := executeUsage(os.Stderr, "new_usage.txt", UsageDataNew{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *New) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value

			case "force":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.force = b
				} else {
					c.force = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument name
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.name = argVal
		}
	}

	if err := commands.ProfileNew(c.profile, c.force, c.name); err != nil {
		return fmt.Errorf("new failed: %w", err)
	}

	return nil
}

func (c *Profile) NewNew() *New {
	set := flag.NewFlagSet("new", flag.ContinueOnError)
	v := &New{
		Profile:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")

	set.BoolVar(&v.force, "force", false, "Forcefully overwrite")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
