// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*Next)(nil)

type Next struct {
	*Disk
	Flags          *flag.FlagSet
	profile        string
	dedicatedIndex int
	diskSizeMb     int
	create         bool
	dry            bool
	SubCommands    map[string]Cmd
}

type UsageDataNext struct {
	*Next
	Recursive bool
}

func (c *Next) Usage() {
	err := executeUsage(os.Stderr, "next_usage.txt", UsageDataNext{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Next) UsageRecursive() {
	err := executeUsage(os.Stderr, "next_usage.txt", UsageDataNext{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Next) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value

			case "dedicatedIndex", "1":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.dedicatedIndex = iv

			case "diskSizeMb", "disk-size-mb":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.diskSizeMb = iv

			case "create":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.create = b
				} else {
					c.create = true
				}

			case "dry":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.dry = b
				} else {
					c.dry = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := commands.DiskNext(c.profile, c.dedicatedIndex, c.diskSizeMb, c.create, c.dry); err != nil {
		return fmt.Errorf("next failed: %w", err)
	}

	return nil
}

func (c *Disk) NewNext() *Next {
	set := flag.NewFlagSet("next", flag.ContinueOnError)
	v := &Next{
		Disk:        c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")

	set.IntVar(&v.dedicatedIndex, "dedicatedIndex", -1, "Use the podcast index number at start of column using this makes the podcast dedicated")
	set.IntVar(&v.dedicatedIndex, "1", -1, "Use the podcast index number at start of column using this makes the podcast dedicated")

	set.IntVar(&v.diskSizeMb, "disk-size-mb", 600, "The disk size in MB")

	set.BoolVar(&v.create, "create", false, "Create disk if not found")

	set.BoolVar(&v.dry, "dry", true, "When this is true it's a dry run and doesn't save changes")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
