// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/arran4/podcast-cdr-manager/commands"
)

var _ Cmd = (*Skill)(nil)

type Skill struct {
	*RootCmd
	Flags         *flag.FlagSet
	profile       string
	SubCommands   map[string]Cmd
	CommandAction func(c *Skill) error
}

type UsageDataSkill struct {
	*Skill
	Recursive bool
}

func (c *Skill) Usage() {
	err := executeUsage(os.Stderr, "skill_usage.txt", UsageDataSkill{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Skill) UsageRecursive() {
	err := executeUsage(os.Stderr, "skill_usage.txt", UsageDataSkill{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Skill) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "profile":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.profile = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("skill failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewSkill() *Skill {
	set := flag.NewFlagSet("skill", flag.ContinueOnError)
	v := &Skill{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.profile, "profile", "", "TODO: Add usage text")
	set.Usage = v.Usage

	v.CommandAction = func(c *Skill) error {

		commands.Skill(c.profile)
		return nil
	}

	v.SubCommands["inspect"] = v.NewInspect()

	v.SubCommands["install"] = v.NewInstall()

	v.SubCommands["list"] = v.NewList()

	v.SubCommands["remove"] = v.NewRemove()

	v.SubCommands["update"] = v.NewUpdate()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
